export const GET_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
export const GET_SUCCESS_PRODUCT = "GET_SUCCESS_PRODUCT"
export const GET_FAIL_PRODUCT = "GET_FAIL_PRODUCT"

export const POST_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
export const POST_SUCCESS_PRODUCT = "GET_SUCCESS_PRODUCT"
export const POST_FAIL_PRODUCT = "GET_FAIL_PRODUCT"