export const GET_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
export const GET_SUCCESS_PRODUCT = "GET_SUCCESS_PRODUCT"
export const GET_FAIL_PRODUCT = "GET_FAIL_PRODUCT"

export const POST_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
export const POST_SUCCESS_PRODUCT = "GET_SUCCESS_PRODUCT"
export const POST_FAIL_PRODUCT = "GET_FAIL_PRODUCT"

export const DELETE_REQUEST_PRODUCT="DELETE_REQUEST_PRODUCT"
export const DELETE_SUCCESS_PRODUCT="DELETE_SUCCESS_PRODUCT"
export const DELETE_FAIL_PRODUCT="DELETE_FAIL_PRODUCT"

export const UPDATE_REQUEST_PRODUCT="UPDATE_REQUEST_PRODUCT"
export const UPDATE_SUCCESS_PRODUCT="UPDATE_SUCCESS_PRODUCT"
export const UPDATE_FAIL_PRODUCT="UPDATE_FAIL_PRODUCT"

export const CART_REQUEST = "GET_CART_REQUEST"
export const CART_SUCCESS = "GET_ CART_SUCCESS"
export const CART_FAIL = "GET_CART_FAIL"